name: nasa_apis
description: A wrapper for the NASA Open APIs with caching and helpful utilities for seamless integration.
version: 0.0.6
repository: https://github.com/voidari/flutter_nasa_apis
issue_tracker: https://github.com/voidari/flutter_nasa_apis/issues

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  path: ^1.8.2
  persist_notifier: ^1.1.1
  sqflite: ^2.1.0+1
  timezone: ^0.10.0
  tuple: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# The following section is specific to Flutter packages.
flutter:
